services:
  db:
    image: postgres:15
    container_name: postgres-db-final
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Verity123
      POSTGRES_DB: Verity_project
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - rede-interna

networks:
  rede-interna:
    driver: bridge